### ISSUE TITLE
suggestion to solr request - make it a phrase

### ISSUE THREAD

**Issue by RastislavHudak** [phaidra/phaidra-vue-components#5]
The suggestions are currently infix and return whole object titles, so if user clicks on some suggestion returned from autocomplete he probably wants to search for that object title - it makes sense to put the whole suggestion into double quotes then before using it as Solr query, to make it a phrase.

Initial problem: if a suggested title contains possible search operators, like
`2: Suffisso d'origine ligure in -mo, -ma nelle voci Balma, Calmus ed altre`
and it's not sent as a phrase, Solr would understand -mo and -ma as exclusion and the object would not be found at all.

@styts : I added this since it's just a trivial change but feel free to ignore anything that comes after the contracted issues.

**Comment by styts** [comment]
I thought that alternatively one would expect to be redirected to the Details page for the given item.
But if you click on a search term that can give many results, i.e. "Ludwig Boltzmann" - you want to see all results, so that is the correct behaviour.

So if you have only one result, you'll see the search with one result - one extra click for the user.

**Comment by RastislavHudak** [comment]
Yup, I think that's ok for now.
