### ISSUE TITLE
Consider giving PDLicense props: o, p meaningful names

### ISSUE THREAD

**Issue by styts** [phaidra/phaidra-vue-components#8]
I'm getting some `Missing required prop: "o"` when the license component is being called from the details page (PDUwmetadata).

```html
<p-d-license v-if="indexdata.dc_license" :dclicense="indexdata.dc_license[0]"></p-d-license>
```
I gave up trying to figure out what the the props should mean. Perhaps consider giving them better names, or document what the props mean (if that's some convention that I'm not familiar with).

https://github.com/phaidra/phaidra-vue-components/blob/e75abd1151bd782188896e6cabfa528e971f5eef/src/components/display/PDLicense.vue#L23-L31

**Comment by RastislavHudak** [comment]
Ah, sorry for that!
* PDUwmetadata is not important now - I'll fix it at some point
* 'o' and 'p' are meaningful once you realize the components are displaying parts RDF metadata (if object has JSON-LD). 'p' means 'predicate' and 'o' means 'object'. Honestly, I think 'o' or 'p' are just fine since words like 'object' or 'predicate' are not very helpful anyways :) I think the confusion comes from the fact that Uwmetadata is not RDF and if PDLicense is used in that context it does not make sense, it's some broken code. I was working on RDF since I needed it to work for some projects and did not care if I do uwmetadata-compatible changes on detail page because uwmetadata do work old frontend so it wasn't necessary that it works here right now - I'd need to fix that at some point.
